### ISSUE TITLE
What license is this project under?

### ISSUE THREAD

**Issue by edk** [kyleburton/base-app#2]
Hi,

I was wondering if you wouldn't mind adding a license file so potential users would know what permissible use terms are.  I'm bringing this up as this is a required dependency of credit_card_validator.

Thank you,

**Comment by kyleburton** [comment]
I just added MIT as the license to the gemspec and released 1.0.6 with that change.  Does that work for you?

**Comment by edk** [comment]
Sweet, Thanks!
